CREATE TABLE if not exists furnitures (
id BIGINT PRIMARY KEY GENERATED AlWAYS AS IDENTITY,
seller_id BIGINT NOT NULL,
name VARCHAR(255) NOT NULL,
type VARCHAR(255) NOT NULL,
material VARCHAR(255) NOT NULL,
color VARCHAR(255) NOT NULL,
price DECIMAL NOT NULL,
status VARCHAR(50) NOT NULL DEFAULT 'brouillon',
created_at TIMESTAMP DEFAULT NOW(),
updated_at TIMESTAMP DEFAULT NOW()
);
