CREATE TABLE IF NOT EXISTS carts (
    id BIGINT PRIMARY KEY GENERATED AlWAYS AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT NOW()
);
