CREATE TABLE IF NOT EXISTS cart_items (
    id BIGINT PRIMARY KEY GENERATED AlWAYS AS IDENTITY,
    cart_id BIGINT NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
    furniture_id BIGINT NOT NULL REFERENCES furnitures(id) ON DELETE CASCADE,
    quantity INT NOT NULL DEFAULT 1
);

